### ISSUE TITLE
Handling unit discrepancies in key_map

### ISSUE THREAD

**Issue by steigersg** [HWO-Yield-Visualizations/yieldplotlib#36]
Noticed this for the input .ayo files and EXOSIMS JSON, but is likely also present elsewhere in the key map. 

Some of the keys represent the same value (i.e. the detector pixel scale) but AYO may define it in terms of arcseconds whereas EXOSIMS uses milliarcseconds. This can be even more complicated since for EXOSIMS you can sometimes specify what units are being provided via a key in the input JSON.

Need to think of a good way to handle/book keep this whether that's defining our own internal unit consistency that we transform all values to comply with or using a tool like astropy units.

**Comment by CoreySpohn** [comment]
I think assigning astropy units when loading them is probably the easiest way to book keep these. The ayo input loader parse the provided units into astropy and the EXOSIMS one should probably do the same since EXOSIMS is already set up with astropy in mind. It could be something where we have to add an "EXOSIMS_unit" column to the spreadsheet or something.
